# = jetty_path key
# each environment can have a jetty_path with absolute or relative
# (to app root) path to a jetty/solr install. This is used
# by the rake tasks that start up solr automatically for testing
# and by rake solr:marc:index.  
#
# jetty_path is not used by a running Blacklight application
# at all. In general you do NOT need to deploy solr in Jetty, you can deploy it
# however you want.  
# jetty_path is only required for rake tasks that need to know
# how to start up solr, generally for automated testing. 
#

# Note: tottenham is the oldest, version 4 of SolrCloud, and has no collections using a current Discovery schema - you can't use it here

development:
  adapter: solr
  url:  <%= ENV['SOLR_URL'] || 'http://localhost:8983/solr/discovery' %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://solrcloud-test.library.ualberta.ca:8080/solr/discovery-test" %> # temporarily out of service starting Oct 4, 2017; being upgrade to v6.6

production:
  adapter: solr
  url: "http://solrcloud-prod.library.ualberta.ca:8080/solr/discovery-prod"
